reverse/grace_reverse.js
reverse/reverse.html
reverse/reverse.js

Grace branch

---

reverse/Liams_Branch.js

Liams branch

---

reverse/ahmed_reverse.js

Ahmed feature

---

reverse/funminiyi_reverse.js

Funminiyi feature

---

reverse/oladimeji_reverse.js

kindly check dis out........still learner

added oladimeji_reverse.js

---

reverse/nwendy_reverse.js

I finally get it!!!, here's it is.

Nwendy feature

---

reverse/tosinn_reverse.js

Hello Tosin,
Kindly check my code.

Tosinn feature

---

reverse/alaba_reverse.js

Hi, Tosin, I have put up my working code, please check it out.

Alaba feature

---

reverse/dipo1_reverse.js
reverse/dipo_reverse.js

Dipo feature

---

reverse/sirolad_reverse.js

Sirolad's reverse file

---

reverse/wilson_reverse.js

Wilson feature

---

reverse/reverse.js
reverse/tosin_reverse.js

Hi Tosin,
I have done stuffs on reverse string, I hope it helps.

added reverse.js

---

celsius/eche_convertCelsius.js
reverse/echezona_reverse.js

this is my function for the conversion to Fahrenheit. Thank you sir

Echezona feature

---

celsius/wilson_celcius.js

my temp conversion from celsius to fahrenheit done.

commited my temp conversion file

---

celsius/olumide_celsius.js
reverse/olumide_reverse.js

Please check this though it still prints vertically. I'm working on something better.

Olumide feature

---

celsius/Lumex_celsius.js

Thanks bro, always a nice day with you.

Lumex added Lumex_celsius.js

---

celsius/nate_celsius.js

my solution

---

celsius/sirolad_convert.js

sirolad temperature conversion

---

largest/eche_oddNumbersInArray.js
largest/eche_sumofarray.js
largest/l_eche.js

committing all 3 assignments, Mr Adesanya

---

Funminiyi/funminiyi_arrayodd.js
Funminiyi/funminiyi_arraysum.js
largest/l_funminiyi.js

Mr Tosin
Here is the JS that return the largest number in an array. Kindly help check and confirm

Here is the JS function that returns the largest number in an array
